openapi: 3.0.1
info:
  title: WASAPhoto
  description: |
    This API allows to manage an instagram-like web application
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: '^.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
           application/json:
            schema:
              type: object
              properties:
                identifier:
                  # change here if you decide to use an integer
                  # or any other type of identifier
                  type: string
                  example: "abcdef012345"
  /profiles/{userId}:
    get:
      tags: ["user"]
      operationId: getUserProfile
      summary: Return one user profile
      description: |
        Get the user with associated userId
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          description: Downloaded the specified user profile page
          content:
            multipart/mixed:
              schema:
                $ref: "#/components/schemas/thumbnailObject"
            application/json:
              schema:
                description: |
                  Information object with photo number, follower list and following list
                type: object
                properties:
                  nPhoto:
                    type: integer
                  followers:
                    type: array
                    items:
                      type: string
                  following:
                    type: array
                    items:
                      type: string
                  
        "404":
          description: User not found
    post:
      tags: ["user"]
      operationId: setMyUserName
      summary: set the user name
      description: Allow to set a new username
      parameters:
        - $ref: "#/components/parameters/userId"
      requestBody:
        content:
          application/json:
            schema:
              description: The new username
              type: string
      responses:
        "200":
          description: Username updated, everything fine
        "400":
          description: The username is not allowed
        
  /myStream:
    get:
      tags: ["user"]
      operationId: getMyStream
      summary: Return logged user stream
      description: |
        Get the user stream
      responses:
        "200":
          description: Downloaded the user stream
          content:
            multipart/mixed:
              schema:
                $ref: "#/components/schemas/thumbnailObject"

      
components:
  parameters:
    userId:
      name: userId
      in: path
      required: true
      description: an user Id to search
      schema:
        type: string
  schemas:
    thumbnailObject:
      description: |
        A rappresentation of a thumnail pic with other informations
      type: array
      items:
        type: object
        properties:
          thumbnailImage:
            type: string
            format: binary
          dateTime:
            type: string
            format: date-time
          nLikes:
            type: integer
          nComments:
            type: integer


